### ISSUE TITLE
Data from 3/26 and 3/27

### ISSUE THREAD

**Issue by m1arc00** [rbracco/IHME_history#1]
[ihme-covid19.zip](https://github.com/rbracco/IHME_history/files/4434714/ihme-covid19.zip)
[ihme-covid19 (2).zip](https://github.com/rbracco/IHME_history/files/4434723/ihme-covid19.2.zip)

**Comment by rbracco** [comment]
Thank you! I will add them to the repo and credit you for the contribution. I will also add a disclaimer as I have no way of personally validating the data, but I will reach out to the IHME team and ask them for confirmation
